services:
  balance-app:
    build: .
    container_name: balance-go-app
    ports:
      - '3003:8080'
    volumes:
      - .:/app
    depends_on:
      - balance-db

  balance-db:
    image: mysql:5.7
    container_name: balance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: balance
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
