services:
  mysql:
    image: mysql:5.7
    container_name: walletcore-balance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_balance
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
