services:
  wallet-app:
    build: .
    container_name: walletcore-go-app
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - wallet-db

  wallet-db:
    image: mysql:5.7
    container_name: walletcore-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql
