POST http://localhost:8080/clients
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@doe.com"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
  "client_id": "444f3c27-ebc1-4be9-b59e-4689fe7f16a9"
}

###

POST http://localhost:8080/transactions
Content-Type: application/json

# The following ids are already in the database
{
  "account_from_id": "14c4e358-06d4-4031-b7e0-fe56662c6e97", 
  "account_to_id": "d9b93621-3b57-4755-b0e5-0bce147c7c3a",
  "amount": 1
}